name: Build

on:
  push:
    branches: [ master ]
jobs:      
  build-mac:
    runs-on: macos-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.3
      with:
        cmake-version: '3.16.x'
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - uses: actions/checkout@v2
    - name: Create build
      run: |
        mkdir build && cd build
        cmake ../
        make
